### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by braveh4rt** [wanproxy/wanproxy#10]
Hi,

when i complie errors occurs.

`make[3]: Entering directory `/home/vincent/wanproxy-master/common/test/buffer-append1'
g++  -o buffer-append1 buffer-append1.o buffer.o log.o 
buffer-append1.o: In function `cmpset<unsigned int, unsigned int>':
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
buffer-append1.o: In function `add<int>':
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:54: undefined reference to `__sync_fetch_and_add_4'
buffer-append1.o: In function `cmpset<unsigned int, unsigned int>':
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
/home/vincent/wanproxy-master/common/test/buffer-append1/../../../common/thread/atomic.h:84: undefined reference to `__sync_bool_compare_and_swap_4'
collect2: ld returned 1 exit status
make[3]: *** [buffer-append1] Error 1
make[3]: Leaving directory `/home/vincent/wanproxy-master/common/test/buffer-append1'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/vincent/wanproxy-master/common/test'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/vincent/wanproxy-master/common'
make: *** [all] Error 2
`

what need to do? i got from master branch here.

Is there any tag stable release ?

i want to try the caching of packet.

Thanks

**Comment by caladri** [comment]
Build in programs/wanproxy, not in the top-level directory.
