### ISSUE TITLE
How to calculate compression rate

### ISSUE THREAD

**Issue by dtouzeau** [wanproxy/wanproxy#12]
Have 2 squids with WanProxy 
Browsers -> squid -> wanproxy client -> wanproxy server -> squid -> Internet.

Have these values from the proxy act as master:

	cache	pointer	None
	codec	codec	XCodec
	codec_to_incoming_bytes	size	4087510 (3991kb)
	codec_to_outgoing_bytes	size	242555 (242555b)
	compressor	compressor	zlib
	compressor_level	int	0x0000000000000006
	incoming_to_codec_bytes	size	234582 (229kb)
	outgoing_to_codec_bytes	size	5013624 (4896kb)
	track_statistics	boolean	true

How can i calculate compression rate ?

codec_to_incoming_bytes: Means objects fecthed from the Internet via proxy ?
codec_to_outgoing_bytes: Means compressed protocol sent to Wanproxy client ?

Means 100-((242555/4087510)*100)=95%

**Comment by caladri** [comment]
"incoming" and "outgoing" are the two halves of the connection.  So "incoming_to_codec" means from the incoming connection to the compressor, and "codec_to_incoming" means from the codec to the incoming connection.

The codec deduplicates and compresses data from one half of the connection to the other.  So "incoming_to_codec" then goes through the codec and then the codec passes it long to "codec_to_outgoing".  Likewise the other side.

Without knowing your configuration, one can't say which direction is compressing and which direction is decompressing, which should probably be made clearer in the stats output, to make calculation easier.  (Some configurations are even compressing in both directions.)  Still, with knowledge of your configuration, it should be possible to derive the answer.

(Sorry for the late response; GitHub bugs that aren't bugs tend to be low priority and get handled in batches.  I know it's probably not helpful for you anymore, but at least this way the answer is recorded for future users.)
