### ISSUE TITLE
Is it possible to let wanproxy use upstream proxy?

### ISSUE THREAD

**Issue by swordgreen** [wanproxy/wanproxy#15]
I would like to set ziproxy or compy (https://github.com/barnacs/compy) as an upstream proxy of wanproxy in order to get compressed images in wanproxy stream. Is it possible to set an upstream proxy in wanproxy? Thanky you!

**Comment by caladri** [comment]
WANProxy doesn't care what's on either side of the connection, so you can insert it directly between your clients and the upstream proxy if that's how you want it configured.  There's no provision for making outbound connections through a proxy, however, if that's what you mean.  That could be done easily, to make outbound connections through a SOCKS or HTTP proxy, but it hasn't been implemented.
