### ISSUE TITLE
what is the next step to use wanproxy

### ISSUE THREAD

**Issue by ZTzha** [wanproxy/wanproxy#22]
i have make wanproxy successfully in my server,
then , what is the next step to test?
i have no idea to use wanproxy.....please help

**Comment by itsHugoBao** [comment]
I'm also have no idea on how to use WANProxy. Is there anyone can help? Thx a lot.

**Comment by caladri** [comment]
If the examples on the web site don't suffice, then you probably need to specifically reach out about what you're trying to accomplish.
