### ISSUE TITLE
Compilation error on CentOS 7.2

### ISSUE THREAD

**Issue by bmikhael** [wanproxy/wanproxy#8]
I'm trying to compile the code from Github, I get the following error on CentOS 7.2 with g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o time.o ../../common/time/time.cc
g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o uuid_libuuid.o ../../common/uuid/uuid_libuuid.cc
../../common/uuid/uuid_libuuid.cc:26:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.
make: *** [uuid_libuuid.o] Error 1

**Comment by caladri** [comment]
You need to install libuuid-dev or libuuid-devel or uuid-dev or uuid-devel or whatever your distribution calls the "development" package of libuuid.

**Comment by bmikhael** [comment]
I've installed the following packages before compilation, then the code was compiled without any errors :smile: 

# yum install openssl-devel libuuid-devel
